echo '127.0.0.1 www.twitter.com' | sudo tee -a /etc/hosts
echo '::1 twitter.com' | sudo tee -a /etc/hosts
echo '127.0.0.1 www.facebook.com' | sudo tee -a /etc/hosts
echo '::1 facebook.com' | sudo tee -a /etc/hosts
echo '127.0.0.1 www.whatsapp.com' | sudo tee -a /etc/hosts
echo '::1 whatsapp.com' | sudo tee -a /etc/hosts
echo '127.0.0.1 www.netflix.com' | sudo tee -a /etc/hosts
echo '::1 netflix.com' | sudo tee -a /etc/hosts
echo '127.0.0.1 www.iplayer.com' | sudo tee -a /etc/hosts
echo '::1 iplayer.com' | sudo tee -a /etc/hosts
echo '127.0.0.1 www.tiktok.com' | sudo tee -a /etc/hosts
echo '::1 tiktok.com' | sudo tee -a /etc/hosts
echo '127.0.0.1 www.tumblr.com' | sudo tee -a /etc/hosts
echo '::1 tumblr.com' | sudo tee -a /etc/hosts
echo '127.0.0.1 www.reddit.com' | sudo tee -a /etc/hosts
echo '::1 reddit.com' | sudo tee -a /etc/hosts
echo '127.0.0.1 www.instagram.com' | sudo tee -a /etc/hosts
echo '::1 instagram.com' | sudo tee -a /etc/hosts
echo '127.0.0.1 www.youtube.com' | sudo tee -a /etc/hosts
echo '::1 youtube.com' | sudo tee -a /etc/hosts
